### ISSUE TITLE
[BUG] Erratic behaviour that causes fail to copy error

### ISSUE THREAD

**Issue by verovaleros** [stratosphereips/collectress#20]
**Describe the bug**
For every other execution, we get the error: `copy_file_from_cache: failed`. 

**To Reproduce**

Docker command: 
```
docker run --rm -e TZ=$(readlink /etc/localtime | sed -e 's,/usr/share/zoneinfo/,,' ) -v ${PWD}/data_feeds.yml:/collectress/data_feeds.yml -v ${PWD}/log.json:/collectress/log.json -v ${PWD}/etag_cache.json:/collectress/etag_cache.json -v ${PWD}/data_output:/data ghcr.io/stratosphereips/collectress:main python collectress.py -f data_feeds.yml -e etag_cache.json -w /data
```

The data_feeds.yml file:
```
feeds:
  - name: AIP_blacklist_for_IPs_seen_last_24_hours.csv
    org: stratosphere
    url: https://mcfp.felk.cvut.cz/publicDatasets/CTU-AIPP-BlackList/Todays-Blacklists/AIP_blacklist_for_IPs_seen_last_24_hours.csv
```

**Expected behaviour**
It shouldn't fail that often, and if it does, the error message should be more descriptive. Should the user run the tool again? Why did it fail?
